permalink: '/blog/:year/:title/'
base: http://www.simpletechture.nl
name: SimpleTechture
author: Patrick Kalkman

markdown: redcarpet
highlighter: pygments

# The release of Jekyll Now that you're using
version: v1.1.0

